### ISSUE TITLE
Failing install on Linux (Debian)

### ISSUE THREAD

**Issue by TheethumNandrum** [playi/WonderPy#18]
I'm trying to install this on a Debian 9. Installation is failing with the following: 

Collecting pyobjc-framework-SystemConfiguration==5.1.1 (from PyObjC->WonderPy==0.1.0)
  Using cached https://files.pythonhosted.org/packages/72/d0/5d6b99d8b93bb8cf81f47ff1931b80c79b8528d45008acd7778eb7b21d86/pyobjc-framework-SystemConfiguration-5.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-mKqB76/pyobjc-framework-SystemConfiguration/setup.py", line 19, in <module>
        [ 'Modules/_manual.m' ],
      File "pyobjc_setup.py", line 389, in Extension
        os_level = get_os_level()
      File "pyobjc_setup.py", line 203, in get_os_level
        pl = plistlib.readPlist('/System/Library/CoreServices/SystemVersion.plist')
      File "/usr/lib/python2.7/plistlib.py", line 75, in readPlist
        pathOrFile = open(pathOrFile)
    IOError: [Errno 2] No such file or directory: '/System/Library/CoreServices/SystemVersion.plist'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-mKqB76/pyobjc-framework-SystemConfiguration/

**Comment by paulolc** [comment]
I'm also getting this error on a Raspberry Pi with Raspbian 9 (stretch). I think this is due to this PyObjC dep, which seems to be available only on MacOS. This dependency on MacOS is in fact stated in the Pre requisites section of WonderPy's README. Also inferring from #5 that Linux is not currently supported ;(

From what I see, the PyObjC is used to load the native MacOS dynamic library binary "libWWHAL.dylib" on wwBTLEMgr.py (WWHAL = Wonder Workshop Hardware Abstraction Layer!?). From this library, 2 functions are used: packets2Json and json2Packets to encode and decode the binary packets coming from the robots via bluetooth.

So, to fix this one needs the source for libWWHAL.dylib and compile it for Linux or binary blobs need to be provided for each platform. Either way is ok for me, if a Raspbian blob is provided.

**Comment by elenzil** [comment]
Hi All -
many apologies for being so inactive on this project.
i don't foresee myself or other folks at Wonder Workshop being able to contribute much time in the near future, either.  :/

This issue is definitely a dupe of #5, so i'm closing this one.

@paulolc - i reply to your comment above over in #5.
